; 322471145, 50%
; 318678620, 50%
.ORIG X3000
main:
	ST R0, R0_SAVE_MAIN				; BACKUP REGISTERS
	ST R1, R1_SAVE_MAIN
	ST R2, R2_SAVE_MAIN
	ST R3, R3_SAVE_MAIN
	ST R4, R4_SAVE_MAIN
	ST R5, R5_SAVE_MAIN
	ST R6, R6_SAVE_MAIN
	ST R7, R7_SAVE_MAIN
	AND R0,R0,#0					; INITIALIZE R0 TO 0
	AND R1,R1,#0					; INITIALIZR R1 TO 0
	LD R6 GETNUM_PTR				; LOAD GETNUM ADDRESS ON R6
	JSRR R6							; DO GETNUM
	ADD R0,R2,#0					; STORE THE NUMBER WE GOT ON R0
	JSRR R6							; DO GETNUM AGAIN
	ADD R1,R2,#0					; STORE THE NUMBER WE GOT ON R1
	AND R2,R2,#0					; INITIALIZE R2 TO 0
	LD R6, CALCULATOR				; LOAD CALCULATOR ADDRESS ON R6
	JSRR R6							; CALL R6
	LD R0, R0_SAVE_MAIN				; RESTORE REGISTERS
	LD R1, R1_SAVE_MAIN
	LD R2, R2_SAVE_MAIN
	LD R3, R3_SAVE_MAIN
	LD R4, R4_SAVE_MAIN
	LD R5, R5_SAVE_MAIN
	LD R6, R6_SAVE_MAIN
	LD R7, R7_SAVE_MAIN
HALT

	R0_SAVE_MAIN .FILL #0			; REGISTERS BACKUP LABELS
	R1_SAVE_MAIN .FILL #0
	R2_SAVE_MAIN .FILL #0
	R3_SAVE_MAIN .FILL #0
	R4_SAVE_MAIN .FILL #0
	R5_SAVE_MAIN .FILL #0
	R6_SAVE_MAIN .FILL #0
	R7_SAVE_MAIN .FILL #0
	GETNUM_PTR .FILL x41F4			; GETNUM ADDRESS
	CALCULATOR .FILL x4384			; CALCULATOR ADDRESS
.END
