; 322471145, 50%
; 318678620, 50%
.orig x4320
PrintNum:
	ST R0, R0_SAVE_PRINTNUM						; BACKUP REGISTERS
	ST R1, R1_SAVE_PRINTNUM
	ST R2, R2_SAVE_PRINTNUM
	ST R3, R3_SAVE_PRINTNUM
	ST R4, R4_SAVE_PRINTNUM
	ST R5, R5_SAVE_PRINTNUM
	ST R6, R6_SAVE_PRINTNUM
	ST R7, R7_SAVE_PRINTNUM
	AND R4,R4,#0								; R4 IS A COUNTER
	AND R5,R5,#0								; R5 IS A NEGATIVE INDEX
	LEA R1,END_ARRAY							; R1 POINTS TO THE END OF THE ARRAY
	LD R6,DIV_PTR								; LOAD DIV ADDRESS ON R6
	ADD R0,R0,#0								; CHECK IF THE NUMBER WE WANT TO PRINT IS NEGATIVE
	BRn NEGATE									; CASE TRUE GO TO "NEGATE"
	LOOP:
		ST R1,R1_SUBSAVE						; BACKUP R1 ON A SUBSAVER
		ST R1,R1_POINTER						; BACKUP R1 ON A R1 POINTER (LABEL)
		LD R1,TEN								; LOAD THE DECMIAL VALUE 10 ON R1
		JSRR R6									; CALL DIV, R2=RESULT AND R3=REMAINDER
		LD R1,R1_SUBSAVE						; RESTORE R1 ORIGINAL VALUE
		STI R3,R1_POINTER						; STORE THE DIV REMAINDER ON THE ADDRESS THAT R1 POINTER POINTS AT IN THE ARRAY
		ADD R1,R1,#-1							; POINT R1 TO THE PREVIOUS INDEX IN THE ARRAY
		ADD R4,R4,#1							; R4++, INCREASE COUNTER
		ADD R0,R2,#0							; R0 = DIV RESULT
		ADD R2,R2,#0							; DIV RESULT = 0?
		BRnp LOOP								; IF TRUE START PRINTING, ELSE CONTINUE DIVISION
		PRINTING:								
			LD R1,R1_POINTER					; NOW R1 POINTS TO THE MOST SIGNIFICANT NUMBER IN THE ARRAY
			ADD R5,R5,#0						; CHECK IF THE NEGATIVE FLAG IS TRUE
			BRp PRINT_MINUS						; IF TRUE THEN GO TO "PRINT_MINUS"
			PRINTING_LOOP:
			ADD R4,R4,#0						; CHECK THE COUNTER (HOW MANY TIMES WE DIVIDE)
			BRz END_PRINT						; IF 0 DIVISIONS THEN END PRINT (NO NUMBER TO PRINT)
			ST R4,R4_SUBSAVE					; STORE COUNTER VALUE ON SUBSAVE
			LD R4,ZERO_ASCII					; LOAD "0" ASCII VALUE ON R4
			LDI R0,R1_POINTER					; LOAD ON R0 THE ADDRESS IN THE ARRAY WHICH R1 POINTER POINTS TO
			ADD R0,R0,R4						; R0=R0+R4 WHICH MAKES THE DECIMAL VALUE IN R0 IN TO ITS CURRECT ASCII CHARACTER
			OUT									; PRINT THE CHARACTER
			LD R1,R1_POINTER					; LOAD THE ADDRESS WHICH R1 POINTER POINTS TO ON TO R1
			ADD R1,R1,#1						; R1 WILL NOW POINT TO THE NEXT INDEX IN THE ARRAY
			ST R1,R1_POINTER					; STORE THE ADDRESS WHICH R1 POINTS TO ON R1 POINTER
			LD R4,R4_SUBSAVE					; RESTORE THE COUNTER VALUE OF R4
			ADD R4,R4,#-1						; R1--, DECREASE COUNTER
			BRz END_PRINT						; IF COUNTER IS 0 THEN END PRINT
			BR PRINTING_LOOP					; ELSE DO PRINTING LOOP AGAIN
	
	PRINT_MINUS:								; CASE R0 IS NEGATIVE
		LD R0, MINUS_ASCII						; LOAD "-" ASCII VALUE ON R0
		OUT										; PRINT "-"
		AND R0,R0,#0							; INITIALIZE R0 TO 0
		BR PRINTING_LOOP						; START PRINTING LOOP
	
    NEGATE:											
		ADD R5,R5,#1							; R5 IS A NEGATIVE INDEX
		BR LOOP                				    ; START DIVISION LOOP
	
	END_PRINT:									; END PRINT
	LD R0, R0_SAVE_PRINTNUM						; RESTORE REGISTERS BACKUP
	LD R1, R1_SAVE_PRINTNUM
	LD R3, R3_SAVE_PRINTNUM
	LD R4, R4_SAVE_PRINTNUM
	LD R5, R5_SAVE_PRINTNUM
	LD R6, R6_SAVE_PRINTNUM
	LD R7, R7_SAVE_PRINTNUM
RET
R0_SAVE_PRINTNUM .FILL #0						; REGISTERS BACKUP LABELS
R1_SAVE_PRINTNUM .FILL #0
R2_SAVE_PRINTNUM .FILL #0
R3_SAVE_PRINTNUM .FILL #0
R4_SAVE_PRINTNUM .FILL #0
R5_SAVE_PRINTNUM .FILL #0
R6_SAVE_PRINTNUM .FILL #0
R7_SAVE_PRINTNUM .FILL #0
R1_SUBSAVE .FILL #0								; R1 SUBSAVE
R4_SUBSAVE .FILL #0								; R4 SUBSAVE
START_ARRAY .FILL #0							; START OF THE ARRAY
			.FILL #0
			.FILL #0
			.FILL #0
END_ARRAY	.FILL #0							; END OF THE ARRAY
END_ARRAY_PRINT   .STRINGZ "\0"					; END OF ARRAY PRINTING
ZERO_ASCII .FILL #48							; 0 ASCII VALUE
R1_POINTER .FILL #0								; R1 POINTER LABEL
MINUS_ASCII .FILL #45							; "-" ASCII VALUE
TEN .FILL #10									; LABEL WITH THE VALUE 10
DIV_PTR .FILL x4064								; POINTER TO DIV
.end